### PR TITLE
Bundle also the production dependencies

### PR DESCRIPTION
**Pull request by MTRNord**
This bundles more of the dependencies and reduces the PR overload

### CODE REVIEW

**Review by HarHarLinks — APPROVED** [review]
you could also dedupe the `package-ecosystem: 'docker'`

**Comment by MTRNord** [comment]
This repo is currently not able to merge PRs anyway. Hence keeping it as is until that is fixed :/

**Comment by HarHarLinks** [comment]
> This repo is currently not able to merge PRs anyway. Hence keeping it as is until that is fixed :/

it is, you just merged #650 today

**Comment by MTRNord** [comment]
> > This repo is currently not able to merge PRs anyway. Hence keeping it as is until that is fixed :/
> 
> it is, you just merged #650 today

hm ok that had a CI fail originally. Or I confused repos. Oops

**Pull request merged**
